# Generated by Django 5.1.6 on 2025-02-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='featured_artists',
            field=models.ManyToManyField(blank=True, related_name='featured_artists', to='songs.artist'),
        ),
    ]
