# Generated by Django 5.1.6 on 2025-02-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_genre_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(max_length=200),
        ),
    ]
