# Generated by Django 5.1.6 on 2025-02-07 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_song_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
