# Generated by Django 5.1.6 on 2025-02-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_album_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
