# Generated by Django 5.1.6 on 2025-02-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_alter_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
