# Generated by Django 5.1.6 on 2025-02-07 03:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_song_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
